"""Emitters — render canonical model objects to presentation formats.

The workflow JSON is the source of truth; the mermaid `.mermaid` file
checked in alongside it is regenerated by `emitter.mermaid.emit_mermaid`.
Pre-commit hooks or CI checks should verify the file is up-to-date with
the JSON.
"""

from workflow.core.emitter.mermaid import emit_mermaid

__all__ = ["emit_mermaid"]
