"""Emit `docs/invariants.md` from the invariant registry.

The registry (`workflow.core.invariants`) is the single source of truth; this
emitter renders it to a byte-stable markdown table so the checked-in document
can be drift-checked in CI (regenerate, then `git diff --exit-code`), exactly
like the per-workflow generated docs.

Regenerate with:

    python -m workflow.core.emitter.invariants
"""

from __future__ import annotations

from pathlib import Path

# Importing the validator populates the registry with the validator-layer
# invariants (the @invariant decorators run at import time). Parser and planner
# layers register themselves the same way once their modules are imported.
import workflow.core.validator  # noqa: F401  (import for registration side effect)
from workflow.core.invariants import LAYERS, all_invariants

_LAYER_BLURB = {
    "parser": "Shape and single-artifact rules — checked at parse time (`ParseError`).",
    "validator": (
        "Cross-artifact and whole-graph rules — checked by `validate-workflow` "
        "(`ValidationFinding`; the only layer that may emit a WARNING)."
    ),
    "planner": "Live-issue marker preconditions — checked at operation time (`OperationError`).",
}


def emit_invariants_doc() -> str:
    """Render the invariant registry as a deterministic markdown document."""
    lines: list[str] = [
        "# Invariants",
        "",
        "<!-- GENERATED by `python -m workflow.core.emitter.invariants` — do not edit by hand. -->",
        "",
        "Every constraint the framework enforces, with the layer that enforces it and",
        "the principle it derives from. This is generated from the invariant registry",
        "(`workflow/core/invariants.py`); see [ADR-0004](adr/0004-invariant-registry-and-guard-placement.md)",
        "for the guard-placement principle and [state-machine-principles.md](state-machine-principles.md)",
        "for the design rationale.",
        "",
        "An invariant lives in the layer that has the information to check it:",
        "",
    ]
    for layer in LAYERS:
        lines.append(f"- **{layer}** — {_LAYER_BLURB[layer]}")
    lines.append("")

    for layer in LAYERS:
        invs = [i for i in all_invariants() if i.layer == layer]
        lines.append(f"## {layer.capitalize()} invariants")
        lines.append("")
        if not invs:
            lines.append("_No invariants registered in this layer yet._")
            lines.append("")
            continue
        lines.append("| ID | Severity | Statement | Principle | Enforced by |")
        lines.append("| --- | --- | --- | --- | --- |")
        for inv in invs:
            symbol = inv.enforcing_symbol.rsplit(".", 1)[-1]
            lines.append(
                f"| `{inv.id}` | {inv.severity.value.upper()} | {inv.statement} "
                f"| `{inv.principle}` | `{symbol}` |"
            )
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def _doc_path() -> Path:
    """Repo-root `docs/invariants.md`, resolved from this file's location."""
    # workflow/core/emitter/invariants.py → parents[3] is the repo root.
    return Path(__file__).resolve().parents[3] / "docs" / "invariants.md"


def write_invariants_doc(path: Path | None = None) -> Path:
    """Write the generated doc to `path` (default repo `docs/invariants.md`)."""
    target = path or _doc_path()
    target.write_text(emit_invariants_doc(), encoding="utf-8")
    return target


if __name__ == "__main__":
    written = write_invariants_doc()
    print(f"wrote {written}")
